project:
  type: website
  output-dir: docs

website:
  title: "Hello"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - talks.qmd
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

